dist: xenial
language: node_js
node_js:
  - 15
jobs:
  include:
  - stage: test
    script: make
  - stage: build & push
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - make pull_image image push_image
    if: branch = master AND type = push AND fork = false
    env:
    - DOCKER_USERNAME=internetstandards
    - secure: aI4En+LesuTAi2RvnnYH09AA5ja7WALkDsGOfFLC2IT56T/uES0rYVZoN9DrX1NOgfPExB4fxNV8Q2h5zhF7Fj2Jtl6vKnvZ9aAbjbQyciaZf6ZBDpeXoJ7Z8WrL8XehJMl4bSKhhOZgQiifF9JDeSKSao099KOp79u+R3bRKlqFtr1pEMcRpSux18ZTzPFV62ZRvgr+zQz87JzVdtQDQyn64vQK+u6GJuhs+jy7AWqnj+XZxvEM8pJ/XMw/gUM5t5Xh9PKEvyoZSluJw0LY109PhYJxdv2jCEH6H/RAWMEyTmbzQUE5uHEQy8RUJZI6RzMN4EVKU9FQGfVpDoQF/uUU4OJJAT3OHIvOD+DYoIw2XWaw6CWaPUDQqvLDzq9EEwo2XyJoRWR0qfGshJdS8vFVDIA5KiPTtydysOtchB+YVA9fDhmojKuBfcj106IC4fsAROwZal1t1iYzRCVY7lS8k50EGXwWA9Z6sP19vp9QpwAX3qMTPtUysn3EMjxQxhy6oZreZFxMVlfvzzQ461Q7i6uYfnI2PlQetNbfuJj08wISlxYZiIe4tZkwv+0zhLtYjp1hmGF6b6uReQRsRIWiBXw09eMg+LHSPB+MmvECHLc3O/ZoTXRmXZw0g2ZM0RtLh7gKzMIWckhDl8EyZa59EVJVvTlAorAOd8+hYN0=
